name: check
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: chechout 
        uses: actions/checkout@v6
        with:

          fetch-depth: 0
          persist-credentials: false


      - uses: super-linter/super-linter@v8.6.0
        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v6
        with:
  
          python-version: '3.13' 
      - run: python my_script.py
